### ISSUE TITLE
試してみましたが、動きません。

### ISSUE THREAD

**Issue by simplelife0530** [collelog/tv-recorder#1]
PX-Q3PE4を使用しているので、dockerで動けば、とても便利です。
前提条件（PCSCD停止、px4videoXドライバ）はOKの状態で、動かしてみましたが、完全には動いていません。
Ubuntu 20.04 Desktop（ubuntu-ja-20.04.1-desktop-amd64.iso)

（１）epgstation1-mariadb-mirakc-amd64.yml
こちらは、すんなりインストールできましたが、番組表が作成できません。
tunerも認識し、mirakcも動いていますが、update schedulesがキャンセルされて、そこから進みません。
（２）epgstation1-mariadb-mirakurun-amd64.yml
こちらも、すんなりインストールできましたが、mirakurunが起動しません。EPGStationがmirakurun待ちになっています。
mirakurunのコンテナに入ってみましたが、sudo systemctl status mirakurunなどのコマンドが使えません。

おそらく問題になるのは、mirakcやmirakurunが一番多いと思います。このあたり、docker版でのcheckの仕方など情報あればお願い致します。
mirakcは、以下のコマンドでおおよそわかりました。
sudo docker logs --tail=1000 mirakc

**Comment by simplelife0530** [comment]
(2)で1時間くらい経ったので、以下のコマンド確認してみました。
> sudo docker logs --tail=1000 mirakurun
すると、動作しているようですが、まだまだかかりそうな様子です。
こんなに時間がかかるものなのでしょうか？

**Comment by collelog** [comment]
Dockerが提供するログ確認方法はご認識の通り docker logs コマンドでの確認のみで、こちらで参照できない情報はそれぞれのアプリが出力するログファイルを直接参照するしかありません。
前者に関して、リアルタイムでログを見たい場合は
  docker logs -f コンテナ名
にて確認してください。
後者は実機にて動作させる場合と変わらないので一旦割愛します。

また、当方が作成するDockerコンテナのOSはAlpine Linuxですので、OSレベルでsudoやsystemdは提供していません。
プロセスの起動状態を確認する手段はpsコマンドの使用になります。


(1)や(2)ですが、GitHubからチェックアウトした設定ファイルをそのまま使用されていますでしょうか？
mirakcやMirakurunのチャンネル定義が当時のままですので、このままではmirakcやMirakurun共に正しく動作しません。

AV Watch > BS右旋帯域再編、2月と4月に実施。視聴や録画予約などに注意
https://av.watch.impress.co.jp/docs/news/1299914.html


今現在手元で運用しているのがmirakcのため、mirakcの情報のみ持ち合わせておりませんが、変更を反映されてない情報で動作させてもEPGの取得処理が完了せず、運用が開始できないかと思います。

なので、mirakcの最新設定をコミットしておきました。
チャンネル定義部分に関しては東京23区内であればこのままで動作しますので、定義を見直していない場合は最新のものを使用してみてください。
なお、このファイルを用いてもGR/BS/CSの全情報を取得するのに1時間位は掛かります。

**Comment by simplelife0530** [comment]
> 今現在手元で運用しているのがmirakcのため、mirakcの情報のみ持ち合わせておりますが、変更を反映されてない情報で動作させてもEPGの取得処理が完了せず、運用が開始できないかと思います。
> 
> なので、mirakcの最新設定をコミットしておきました。
> チャンネル定義部分に関しては東京23区内であればこのままで動作しますので、定義を見直していない場合は最新のものを使用してみてください。

情報ありがとうございます。
朝起きて、
sudo docker logs --tail=1000 epgstation
を実行したら、
[2021-03-04T07:41:00.194] [INFO] system - wait mirakurun
[2021-03-04T07:41:06.201] [INFO] system - wait mirakurun
となっていました。

調べたら、2021年2月29日に、こんな情報がありました。
https://github.com/mirakc/mirakc/issues/19

**Comment by collelog** [comment]
リンク先の1年前に発生したトラブルのIssuesは当時から存しておりますが（mirakcは対処済み）、状況を整理させてください。

前提
1)mirakcもMirakurunもチャンネル定義が最新化されていないので、更新しない限りは正常に動作しない
→mirakcはconfig.ymlコミット済み

当方から見た不明点
1)朝確認したepgstationのコンテナログは、mirakcとMirakurunのどちらと連携するEPGStationでしょうか？
2)また、mirakcまたはMirakurunのチューナー定義を正しく修正し、チューナーソフト側でEPG取得処理が完了した上でのお話でしょうか？

mirakcの場合はEPG取得処理が完了せずともEPGStationからのリクエストに対して応答は返すので、コンテナ間の通信が全く出来ていない可能性があります。

Mirakurunの場合は動作を確認していないので何とも言えませんが、前述の通り、チューナー定義を直さないと初期処理が終わらず接続出来ない可能性と、コンテナ間の通信が出来ていない可能性があります。


先月から今月末までは私事の対応に追われて、基本、作業が出来ない状況ですので、どの環境で何が起こったのか整理した情報を頂けたら幸いです。
特にMirakurunは動作未確認のチューナー定義を提供することはできますが、こちらでの実機確認は先の話となるため、当方資産を用いたMirakurunの動作に関してのトラブル支援は暫く滞る見通しです。

**Comment by collelog** [comment]
Mirakurun - EPGStation でご使用の場合は、

Dockerホスト上のファイル
  ./epgstation/config/config.json
内、mirakurunPathをmirakcからmirakurunに変えてみてください。

または、
  ./epgstation/config/config.json
を
  ./example-config/epgstation1-mysql/UNIXdomainsocket/config/config.json
に差し替えてみてください。

前者の場合はmirakcでご使用の場合は再度設定ファイルを変更する必要があります。
後者の場合はUNIXドメインソケット通信を用いますので、mirakc/Mirakurun共通の設定です。
ただしDocker上のMirakurunでUNIXドメインソケット通信を使用する場合、最新のMirakurunでなければ録画ファイルの先頭が欠ける可能性があります（当方環境では発生しておりませんでしたが、最近のMirakurun 3.xでは当問題は解決しています）

**Comment by simplelife0530** [comment]
すみません。
1年前の情報でした。

現在試しているのは、mirakurunです。
既に稼働しているmirakurunと同じchannels.ymlとtuners.ymlを、ファイルを開いて、コピーしています。
channels.ymlもtuners.ymlも完全に同じにしてみました。
一度rebootしてから、ログを確認したところ、mirakurunは正常に動作して、EPGもとれているようです。

mirakcでは通信できていましたが、mirakurunの方ではEPGStationと連携できていないようです。

いろいろ手間をかけていただき、すみません。

こちらには、PX-Q3PE4を搭載したテスト機が3台あるので、いろいろ調査してみます。
まずAlpine Linuxで再現してみます。dockerのLinux違いの影響について興味があったので、
ちょうどいい機会です。
確認できたら、また報告します。

**Comment by simplelife0530** [comment]
解決しました。

tv-recorder/epgstation/config/config.jsonを修正しました。

修正前　　"mirakurunPath": "http://mirakc:40772/",
修正後　　"mirakurunPath": "http://mirakurun:40772/",

これで正常に動きました。
