### ISSUE TITLE
epgstation1での番組表の取得ができません

### ISSUE THREAD

**Issue by lkfejleene** [collelog/tv-recorder#2]
user@TV:~/tv-recorder$ uname -a
Linux TV 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
チューナ：MaxM4
ドライバ：https://github.com/DigitalDevices/dddvb/archive/0.9.37.zip
TVTest + Bon_mirakc.dllでの視聴は確認できております。

git clone https://github.com/collelog/tv-recorder.git

編集箇所
vi epgstation1-mariadb-mirakc-amd64.yml
　・mirac/conf/config.yml
　　　channels:
　　　  - name: ＮＨＫＥテレ１大阪
　　　    type: GR
　　　    channel: 13
　　　　　　～略～
　　　tuners:
　　　  - name: MaxM4
　　　    types:
　　　      - GR
　　　      - BS
　　　      - CS
　　　    command: dvbv5-zap -a 0 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -
　　　　　　～略～

　・/epgstation/config/config.json
　　　　（編集なし）

　・cp epgstation1-mariadb-mirakc-amd64.yml docker-compose.yml
　　　volumes:
（追記） - ./mirakc/conf/dvbv5_channels_isdb.conf:/etc/mirakc/dvbv5_channels_isdb.conf:ro
　　　devices:
            - /dev/dvb

この状況で sudo docker-compose up --build すると、必ず下記WARNが発生し何時間たってもepgstation番組表が取得できません。因みに、epgstationインターフェースは表示できています。

mirakc        | 2021-04-22T13:03:57.613697074+09:00  WARN mirakc_core::epg: Failed to load services: std::io::error: No such file or directory (os error 2)    
mirakc        | 2021-04-22T13:03:57.618517719+09:00  WARN mirakc_core::epg: Failed to load clocks: std::io::error: No such file or directory (os error 2)    
mirakc        | 2021-04-22T13:03:57.618531234+09:00  WARN mirakc_core::epg: Failed to load schedules: std::io::error: No such file or directory (os error 2) 

起動中のmirakcコンテナ内では

user@TV:~/tv-recorder$ docker exec -it mirakc sh
/ # ls -ld /var/lib/mirakc/epg
drwxrwxr-x    2 1000     1000          4096 Apr 22 12:48 /var/lib/mirakc/epg
/ # ls -la /var/lib/mirakc/epg
total 8
drwxrwxr-x    2 1000     1000          4096 Apr 22 12:48 .
drwxr-xr-x    3 root     root          4096 Apr 22 12:56 ..
-rw-rw-r--    1 1000     1000             0 Apr 22 12:48 .gitkeep

となっており、確かにWARN中にある services、clocks、schedules 等のファイルは作られておりません。

・epgバインドマウントについて
epgstation1-mariadb-mirakc-amd64.ymlで
             - ./mirakc/epg:/var/lib/mirakc/epg
となっており、
 ./mirakc/epg　に　touch TESTFILE
とすると
/var/lib/mirakc/epgに、作成したテストファイルTESTFILEが存在しますので
バインドマウントは出来ているように思われます。

以上、表題の番組表取得の件、ご確認いただけないでしょうか？

**Comment by collelog** [comment]
まず、mirakcの(初回)起動時にservices、clocks、schedulesのファイルは無く、起動処理の過程でmirakcのEPG関連ジョブで作成されるものです。
これらのファイル生成が終わらない限りはEPGStationに番組表は表示されません。

collelog/mirakc:latest-alpine-amd64 は、mirakc 1.17.2 が組み込まれているので、
最新のmirakcの修正が反映されている collelog/mirakc:main-alpine-amd64 （mirakc/mirakc:main-alpineをベース）
に変更し試してみて頂けないでしょうか。

それでもファイルの生成が行われない場合は、ログレベルをINFOからDEBUGに変更の上、
mirakc側のEPG関連ジョブの動作を追う事になるかと思います。

トラブルシューティング
 > ログメッセージの確認
https://mirakc.github.io/dekiru-mirakc/troubleshooting.html

**Comment by lkfejleene** [comment]
collelog/mirakc:main-alpine-amd64で試しましたところ、
下記メッセージが色んな色（赤、紫、青…）で表示され続けます(内容は全て同じ)。

mirakc exited with code 101
mirakc        | + rm -rf /var/run/pcscd
mirakc        | Start pcscd
mirakc        | Start mirakc
mirakc        | + mkdir -p /var/run/pcscd
mirakc        | + echo 'Start pcscd'
mirakc        | + echo 'Start mirakc'
mirakc        | + mirakc
mirakc        | + pcscd -f -e
mirakc        | thread 'main' panicked at 'assertion failed: `(left == right)`
mirakc        |   left: `102`,
mirakc        |  right: `96`: config.channels: `name` must be a unique', mirakc-core/src/config.rs:75:9
mirakc        | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

この時、epgstationはブラウザからの接続エラーでインターフェースも表示されず、
TVTestはBonDriverでのチューナ接続エラーとなります。

epgstationは
epgstation    | [2021-04-22T15:52:21.625] [INFO] system - wait mirakurun
とmirakcの処理を待ってる（？）状況です。

**Comment by collelog** [comment]
mirakcの起動が失敗して、Dockerコンテナが再起動を繰り返している状況です。
また、mirakcが起動しないのでepgstationはmirakcへの接続が確立するまで待っています。

>right: 96: config.channels: name must be a unique', mirakc-core/src/config.rs:75:9
のメッセージ通りchannels: のname で重複エラーと言われているので設定を見直す必要がありますが、当方は見たことがないメッセージであり、コミット履歴見ると開発者様が2日前に設定のチェックロジックを入れた様ですね。
・該当source
https://github.com/mirakc/mirakc/blob/main/mirakc-core/src/config.rs
・変更履歴
https://github.com/mirakc/mirakc/commit/64223adba0dbc3c3bd3ebf3e3a014c632a5c5447#diff-6c83c87785225ca674283fc85a0e4219bb3656b33e04217d16eab809d792c94b

単純にchannels: の name で重複エラーなのか当方も試していないので、一旦、チャンネル定義を一個にしつつ増やして試してみる、collelog/tvchannels-scanの出力結果を使ってみる等が考えられます。

**Comment by collelog** [comment]
確認しました。やはりchannelsのnameの重複があると該当メッセージが出る様です。
今後このような仕様になると思われるので、config.ymlを編集せざる得ないですね。

エラー発生例

    name: 'ＢＳ－ＴＢＳ'
    type: 'BS'
    channel: 'BS1_1'
    services: [161]

    name: 'ＢＳ－ＴＢＳ'
    type: 'BS'
    channel: 'BS1_1'
    services: [162]

エラー回避例

    name: 'ＢＳ－ＴＢＳ 161'
    type: 'BS'
    channel: 'BS1_1'
    services: [161]

    name: 'ＢＳ－ＴＢＳ 162'
    type: 'BS'
    channel: 'BS1_1'
    services: [162]

**Comment by lkfejleene** [comment]
なる程です。＞nameの重複
因みにこれ、同様にデバイスnameでも発生しますね。

以下エラー
  - name: MaxM4
    types:
      - GR
      - BS
      - CS
    command: dvbv5-zap -a 0 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -
    
  - name: MaxM4
    types:
      - GR
      - BS
      - CS
    command: dvbv5-zap -a 1 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

以下起動成功
  - name: MaxM4_0
    types:
      - GR
      - BS
      - CS
    command: dvbv5-zap -a 0 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -
    
  - name: MaxM4_1
    types:
      - GR
      - BS
      - CS
    command: dvbv5-zap -a 1 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

で、番組表の件ですが、仰られたように初回起動では矢張り、

mirakc        | 2021-04-22T16:50:43.652225305+09:00  WARN mirakc_core::epg: Failed to load services: std::io::error: No such file or directory (os error 2)    
mirakc        | 2021-04-22T16:50:43.656292688+09:00  WARN mirakc_core::epg: Failed to load clocks: std::io::error: No such file or directory (os error 2)    
mirakc        | 2021-04-22T16:50:43.656301225+09:00  WARN mirakc_core::epg: Failed to load schedules: std::io::error: No such file or directory (os error 2)  

ですが、2回めのコンテナ起動からは番組表の取得を確認しました。
（と言ってもまだ全部の局を取得したわけではありませんが…）

調査とご対応、ありがとうございました。

**Comment by lkfejleene** [comment]
今度は衛星が全くスキャンも受信もできなくなってます。。。
地上波は問題ないんですが。

mirakc        | 2021-04-22T18:02:32.560528802+09:00 DEBUG mirakc_core::command_util: dvbv5-zap#125: ERROR    frequency 1317.84MHz (tune freq 1317.84MHz) is out of LNBf Japan 110BS/CS LNBf range 

この問題に関しては、masnagamさんへの新規issueという事になりますでしょうか？

**Comment by collelog** [comment]
該当ログだけみたらチューナーコマンドのエラーが出ている様ですが、これはまず切り分けが必要ですね。

1) mirakcコンテナでチューナーコマンド単体で実行したら、正常にファイルが保存できるか
2) 想定されるコマンドとログ・設定のcommand記載を比較し、想定通り実行されているか

mirakcコンテナはmirakc 1.17.2、mainともにAlpine Linux 3.13.5
インストールされているv4l-utils-dvbv5のバージョンは1.20.0-r0
https://pkgs.alpinelinux.org/packages?name=v4l-utils-dvbv5&branch=v3.13

2)で問題があるならmirakc側に相談がよろしいかと思います。
1)であればチューナーコマンドを変えないといけないかもしれません。こちら、パッケージやアプリの組込みに関しては当方が相談に乗ることはできます。ただし、DD Max M4は所有していないので動作テストは出来ないです。

**Comment by lkfejleene** [comment]
試した結果、
　1)はOK。
　2)に問題あり。先の報告通り衛星を全く受け付けません。
でした。
masnagamさんにissue上げてみようと思います。
お付き合いありがとうございました。

なお主題の番組表の件は地上波のみですが表示されましたので勝手ながらcloseとさせてください。
ご対応感謝いたします。ありがとうございました。
