### ISSUE TITLE
エンコード時にエラーが発生します。

### ISSUE THREAD

**Issue by petit1964** [collelog/tv-recorder#3]
dockerファイルの提供ありがとうございます。

Synology DS920+にepgstation1-mariadb-mirakc-amd64.ymlを入れました。
EPGStationも起動し、番組表の取得、録画ができています。
mp4への変換に失敗します。
logをDEBUGに設定後、epgstation/logs/Service/ststem.logを確認すると
下記が出力されています。

[2021-04-27T19:54:35.945] [DEBUG] system - Error loading shared library libmysofa.so.1: No such file or directory (needed by /usr/local/lib/libavfilter.so.7)
Error loading shared library libsrt.so.1: No such file or directory (needed by /usr/local/lib/libavformat.so.58)
Error loading shared library libcodec2.so.0.9: No such file or directory (needed by /usr/local/lib/libavcodec.so.58)
Error loading shared library libSvtAv1Enc.so.0: No such file or directory (needed by /usr/local/lib/libavcodec.so.58)

uname -aの結果は以下となります。
Linux XXX 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021 x86_64 GNU/Linux synology_geminilake_920+

インストールに不足している物などありましたら、ご教示いただければ幸いです。

**Comment by collelog** [comment]
まず、
sudo docker exec -it epgstation ffmpeg
sudo docker exec -it epgstation ldd /usr/local/bin/ffmpeg
にてffmpegがライブラリを認識しているか確認して頂けないでしょうか？

これらのコマンドで同様のエラーが認識していない場合は、EPGStationによるFFmpeg呼び出し時の問題と切り分けできます。

**Comment by collelog** [comment]
EPGStationのエンコード処理でLD_LIBRARY_PATHが必要であれば
docker-compose.yml 中、epgstationのenvironmentにLD_LIBRARY_PATHを追加してあげれば良いのですが

　environment:
            LD_LIBRARY_PATH: /usr/local/lib64:/usr/local/lib:/usr/lib:/lib

EPGStation側の実装では
https://github.com/l3tnun/EPGStation/pull/431
の様に、v2ではエンコード時にLD_LIBRARY_PATHが渡らず、エラーとなる問題を抱えていたようです。

v2修正箇所
https://github.com/l3tnun/EPGStation/pull/431/commits/eb1c8b81a0f566e9a2e4023517535fca592b9b16

v1ではv2と同様に"PATH: process.env['PATH']"とコーディングされているので、LD_LIBRARY_PATHを環境変数に設定してもv1のソースをいじらない限りはダメかもしれません。
https://github.com/l3tnun/EPGStation/blob/v1/src/server/Model/Service/Encode/EncodeManageModel.ts

**Comment by petit1964** [comment]
回答ありがとうございます。
まず、EPGStation上で録画した番組のサムネイル画像ですが表示されています。
ですので、ffmpeg自体に問題はないかと思います。
また、ご指定のコマンドの結果も問題ないかと思います。
(1) sudo docker exec -it epgstation ffmpeg
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.1 (Alpine 10.2.1_pre1) 20201203
  configuration: --disable-debug --disable-doc --disable-ffplay --disable-filter=resample --disable-stripping --disable-thumb --enable-avisynth --enable-avresample --enable-chromaprint --enable-fontconfig --enable-frei0r --enable-gpl --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libfdk_aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libkvazaar --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzmq --enable-lv2 --enable-nonfree --enable-openal --enable-opengl --enable-openssl --enable-postproc --enable-sdl2 --enable-shared --enable-version3 --extra-cflags='-I/usr/local/include -O2 -pipe -march=x86-64 -mtune=generic' --extra-cxxflags='-I/usr/local/include -O2 -pipe -march=x86-64 -mtune=generic' --extra-ldflags=-L/usr/local/lib --extra-libs='-lpthread -lm' --prefix=/usr/local
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder

(2) sudo docker exec -it epgstation ldd /usr/local/bin/ffmpeg
	/lib/ld-musl-x86_64.so.1 (0x55b599814000)
	libavdevice.so.58 => /usr/local/lib/libavdevice.so.58 (0x7f2c75340000)
	libavfilter.so.7 => /usr/local/lib/libavfilter.so.7 (0x7f2c74f4a000)
	libavformat.so.58 => /usr/local/lib/libavformat.so.58 (0x7f2c74cc2000)
	libavcodec.so.58 => /usr/local/lib/libavcodec.so.58 (0x7f2c73995000)
	libavresample.so.4 => /usr/local/lib/libavresample.so.4 (0x7f2c73973000)
	libpostproc.so.55 => /usr/local/lib/libpostproc.so.55 (0x7f2c73951000)
	libswresample.so.3 => /usr/local/lib/libswresample.so.3 (0x7f2c73931000)
	libswscale.so.5 => /usr/local/lib/libswscale.so.5 (0x7f2c7389e000)
	libavutil.so.56 => /usr/local/lib/libavutil.so.56 (0x7f2c735f1000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x55b599814000)
	libjack.so.0 => /usr/lib/libjack.so.0 (0x7f2c735b5000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x7f2c735a3000)
	libopenal.so.1 => /usr/lib/libopenal.so.1 (0x7f2c7348a000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f2c73463000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x7f2c7345e000)
	libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0x7f2c73459000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x7f2c7344f000)
	libcdio_paranoia.so.2 => /usr/lib/libcdio_paranoia.so.2 (0x7f2c73446000)
	libcdio_cdda.so.2 => /usr/lib/libcdio_cdda.so.2 (0x7f2c7343c000)
	libdc1394.so.25 => /usr/lib/libdc1394.so.25 (0x7f2c733c9000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x7f2c73302000)
	libcaca.so.0 => /usr/lib/libcaca.so.0 (0x7f2c73238000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x7f2c731b2000)
	libpulse.so.0 => /usr/lib/libpulse.so.0 (0x7f2c73167000)
	libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x7f2c73022000)
	libbs2b.so.0 => /usr/local/lib/libbs2b.so.0 (0x7f2c7301b000)
	liblilv-0.so.0 => /usr/lib/liblilv-0.so.0 (0x7f2c73002000)
	librubberband.so.2 => /usr/lib/librubberband.so.2 (0x7f2c72fd7000)
	libmysofa.so.1 => /usr/local/lib64/libmysofa.so.1 (0x7f2c72fae000)
	libflite_cmu_us_awb.so.1 => /usr/lib/libflite_cmu_us_awb.so.1 (0x7f2c72bb8000)
	libflite_cmu_us_kal.so.1 => /usr/lib/libflite_cmu_us_kal.so.1 (0x7f2c72a53000)
	libflite_cmu_us_kal16.so.1 => /usr/lib/libflite_cmu_us_kal16.so.1 (0x7f2c72679000)
	libflite_cmu_us_rms.so.1 => /usr/lib/libflite_cmu_us_rms.so.1 (0x7f2c721df000)
	libflite_cmu_us_slt.so.1 => /usr/lib/libflite_cmu_us_slt.so.1 (0x7f2c71de7000)
	libflite.so.1 => /usr/lib/libflite.so.1 (0x7f2c71db1000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x7f2c71d94000)
	libass.so.9 => /usr/lib/libass.so.9 (0x7f2c71d6d000)
	libvidstab.so.1.1 => /usr/lib/libvidstab.so.1.1 (0x7f2c71d57000)
	libzmq.so.5 => /usr/lib/libzmq.so.5 (0x7f2c71cd2000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f2c71c95000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f2c71be1000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x7f2c71ab7000)
	libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f2c71aa8000)
	libgme.so.0 => /usr/lib/libgme.so.0 (0x7f2c71a69000)
	libopenmpt.so.0 => /usr/local/lib/libopenmpt.so.0 (0x7f2c71854000)
	libchromaprint.so.1 => /usr/lib/libchromaprint.so.1 (0x7f2c71841000)
	libbluray.so.2 => /usr/lib/libbluray.so.2 (0x7f2c717f3000)
	libz.so.1 => /lib/libz.so.1 (0x7f2c717d9000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x7f2c71758000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x7f2c714d7000)
	libsrt.so.1 => /usr/local/lib64/libsrt.so.1 (0x7f2c71430000)
	libssh.so.4 => /usr/lib/libssh.so.4 (0x7f2c713d3000)
	libvpx.so.6 => /usr/lib/libvpx.so.6 (0x7f2c711c0000)
	libwebpmux.so.3 => /usr/lib/libwebpmux.so.3 (0x7f2c711b5000)
	libwebp.so.7 => /usr/lib/libwebp.so.7 (0x7f2c7115f000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7f2c7113c000)
	libaribb24.so.0 => /usr/local/lib/libaribb24.so.0 (0x7f2c71128000)
	libdav1d.so.5 => /usr/lib/libdav1d.so.5 (0x7f2c70ffe000)
	libopencore-amrwb.so.0 => /usr/local/lib/libopencore-amrwb.so.0 (0x7f2c70fe8000)
	librsvg-2.so.2 => /usr/lib/librsvg-2.so.2 (0x7f2c705b8000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x7f2c7056d000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7f2c70466000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x7f2c70377000)
	libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x7f2c7036c000)
	libaom.so.0 => /usr/lib/libaom.so.0 (0x7f2c6ff4d000)
	libcodec2.so.0.9 => /usr/local/lib64/libcodec2.so.0.9 (0x7f2c6feab000)
	libfdk-aac.so.2 => /usr/lib/libfdk-aac.so.2 (0x7f2c6fdbe000)
	libgsm.so.1 => /usr/lib/libgsm.so.1 (0x7f2c6fdb1000)
	libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x7f2c6fd45000)
	libopencore-amrnb.so.0 => /usr/local/lib/libopencore-amrnb.so.0 (0x7f2c6fd19000)
	libopenjp2.so.7 => /usr/lib/libopenjp2.so.7 (0x7f2c6fcc9000)
	libopus.so.0 => /usr/lib/libopus.so.0 (0x7f2c6fc69000)
	libshine.so.3 => /usr/lib/libshine.so.3 (0x7f2c6fa5d000)
	libspeex.so.1 => /usr/lib/libspeex.so.1 (0x7f2c6fa45000)
	libSvtAv1Enc.so.0 => /usr/local/lib64/libSvtAv1Enc.so.0 (0x7f2c6eaad000)
	libtheoraenc.so.1 => /usr/lib/libtheoraenc.so.1 (0x7f2c6ea74000)
	libtheoradec.so.1 => /usr/lib/libtheoradec.so.1 (0x7f2c6ea5a000)
	libtwolame.so.0 => /usr/local/lib/libtwolame.so.0 (0x7f2c6ea33000)
	libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x7f2c6ea0b000)
	libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x7f2c6e961000)
	libx264.so.157 => /usr/lib/libx264.so.157 (0x7f2c6e644000)
	libx265.so.192 => /usr/lib/libx265.so.192 (0x7f2c6e1d5000)
	libxvidcore.so.4 => /usr/lib/libxvidcore.so.4 (0x7f2c6e108000)
	libkvazaar.so.6 => /usr/local/lib/libkvazaar.so.6 (0x7f2c6e073000)
	libsoxr.so.0 => /usr/lib/libsoxr.so.0 (0x7f2c6e010000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f2c6de6e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f2c6de54000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x7f2c6de4f000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f2c6de47000)
	libcdio.so.19 => /usr/lib/libcdio.so.19 (0x7f2c6de20000)
	libraw1394.so.11 => /usr/lib/libraw1394.so.11 (0x7f2c6de10000)
	libusb-1.0.so.0 => /usr/lib/libusb-1.0.so.0 (0x7f2c6ddf6000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x7f2c6dcd3000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x7f2c6dc76000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x7f2c6dc5b000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x7f2c6dc56000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x7f2c6dc4f000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x7f2c6dc3c000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x7f2c6dc34000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x7f2c6dc2f000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x7f2c6dc28000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f2c6dc05000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x7f2c6dbfe000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x7f2c6dbf9000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x7f2c6dbf1000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x7f2c6dbec000)
	libpulsecommon-14.1.so => /usr/lib/pulseaudio/libpulsecommon-14.1.so (0x7f2c6db74000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x7f2c6db2a000)
	libintl.so.8 => /usr/lib/libintl.so.8 (0x7f2c6db1d000)
	libserd-0.so.0 => /usr/lib/libserd-0.so.0 (0x7f2c6db0c000)
	libsord-0.so.0 => /usr/lib/libsord-0.so.0 (0x7f2c6db02000)
	libsratom-0.so.0 => /usr/lib/libsratom-0.so.0 (0x7f2c6daf8000)
	libsamplerate.so.0 => /usr/lib/libsamplerate.so.0 (0x7f2c6d98b000)
	libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x7f2c6d7c5000)
	libflite_usenglish.so.1 => /usr/lib/libflite_usenglish.so.1 (0x7f2c6d799000)
	libflite_cmulex.so.1 => /usr/lib/libflite_cmulex.so.1 (0x7f2c6d702000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x7f2c6d660000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x7f2c6d620000)
	libsodium.so.23 => /usr/lib/libsodium.so.23 (0x7f2c6d5cd000)
	libuuid.so.1 => /lib/libuuid.so.1 (0x7f2c6d5c4000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f2c6d593000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x7f2c6d586000)
	libmpg123.so.0 => /usr/lib/libmpg123.so.0 (0x7f2c6d543000)
	libvorbisfile.so.3 => /usr/lib/libvorbisfile.so.3 (0x7f2c6d53a000)
	libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x7f2c6d52f000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x7f2c6d50d000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x7f2c6d364000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x7f2c6d354000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x7f2c6d30e000)
	libffi.so.7 => /usr/lib/libffi.so.7 (0x7f2c6d301000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7f2c6d2a5000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x7f2c6d20f000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x7f2c6d200000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x7f2c6d1f4000)
	libogg.so.0 => /usr/lib/libogg.so.0 (0x7f2c6d1ea000)
	libbsd.so.0 => /usr/lib/libbsd.so.0 (0x7f2c6d1d4000)
	libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x7f2c6d163000)
	libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x7f2c6d15c000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x7f2c6d13d000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x7f2c6d11a000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x7f2c6d115000)
	libmount.so.1 => /lib/libmount.so.1 (0x7f2c6d0c4000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x7f2c6d0ad000)
	libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x7f2c6d079000)
	libblkid.so.1 => /lib/libblkid.so.1 (0x7f2c6d031000)

**Comment by collelog** [comment]
EPGStation1.7.6にて試した結果、LD_LIBRARY_PATHを追加しても/usr/local/lib64配下のライブラリは認識しませんでした。
対応としてはソースをいじるか、EPGStation2系を使うかでしょうか。

なお、EPGStation2系のDockerイメージは以前より作成済みのため（Dockerイメージの作成・更新を今月再開したので、最新版まで用意しています）、docker-compose.ymlを用意すれば使用できます。
当方作成のdocker-compose.ymlはＧＷ中にコミットする予定です。

**Comment by petit1964** [comment]
こちらでも、docker-compose.yml内のepgstationセクション environmentにLD_LIBRARY_PATHを追加して確認しました。
同様に効果を確認できませんでした。

EPGStation version 1.7.3では未対策とのこと、了解しました。
本Issueですが、対象バージョンは異なりますが、EPGStation 最新バージョン向けdocker-compose.ymlでの確認完了をもってクローズとしたいのですが、よろしいでしょうか？

**Comment by collelog** [comment]
EPGStation2対応のdocker-compose.ymlと入替え用のconfig(example-config配下)を用意しました。
こちらではRPi4(64bit)向けのみ実機検証しているので、もしかしたら設定を一部修正する必要があるかもしれません。

EPGStation1→2へ移行をする場合はDockerホスト側 ./recorded にEPGStationのDBバックアップ・リストアコマンドの出力/入力ファイルを置く形で作業をすればスムーズにいくかと思います。
なお、これはEPGStationのV1→V2移行または同バージョン間で使用するDBを切り替える場合(MariaDB⇔SQLite)も同じです。
※当方としては個別にコンテナを用意する必要がないSQLite(正規表現対応済み)の使用をおすすめします。

また、ご使用のSynology DS920+のCPUはQSV対応のCeleron J4125ですので、vaap-amd64版のdocker-compose.ymlが上手く動作するかもしれません。
(Dockerコンテナ側のパッケージ整備はしてあるので、SynologyのDMS次第です)
VAAP指定のEPGStation設定(FFmpegの引数修正)は用意していないので、もし設定をいじるのであればフィードバック頂ければ幸いです。

**Comment by petit1964** [comment]
ゴールデンウィーク早々の対応、ありがとうございました。

epgstation2-mirakc-amd64.ymlにて、下記追記なしで無事エンコードできました。
environment:LD_LIBRARY_PATH: /usr/local/lib64:/usr/local/lib:/usr/lib:/lib

vaap-amd64版のdocker-compose.ymlを試してみましたが、残念ながらNGでした。
Error loading shared library libmfx.so.1: No such file or directory (needed by /usr/local/lib/libavfilter.so.7)

本Issueですが、epgstation2-mirakc-amd64.ymlでのエンコード確認完了をもって、クローズとなります。

本当にありがとうございます。
