### ISSUE TITLE
番組表は習得出来るが録画・ストリーミングがうまく動きません

### ISSUE THREAD

**Issue by PierreEmma** [collelog/tv-recorder#4]

**Comment by collelog** [comment]
mirakcとEPGStationのDockerイメージを最新のmasterでビルドしてみました。動作確認は今週中に実施しますので暫くお待ちください。

もしかしたらEPGStation側のmirakurunライブラリのバージョンを変えないとダメかもしれません（事象は違いますが、こういう問題も有る様なので）
https://twitter.com/CxZMoXaYyU8OJzD/status/1460943017318125581?s=20

**Comment by collelog** [comment]
お待たせしました。

事象は恐らくpcscdのサービス起動がうまく動作しなかったからと思われます。
Alpine LinuxまたはOpenRCパッケージの最近行われたマイナーバージョンアップが起因で、一度rc-statusコマンドを実行しないとサービスの起動に支障が出ることを確認しました。

mirakcならびにMirakurunのAlpine Linux版を修正しています。

docker-compose down 後に
docker-compose pull を実行して、Dockerイメージを最新化し動かしてみて下さい。

**Comment by PierreEmma** [comment]
お世話になっております。
無事にDS920で動かすことが出来ました…！
修正頂きましてありがとうございました。
